name: Concurrency-3-matrix
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [10, 12, 14]
        os: [ubuntu-latest, windows-latest]
      max-parallel: 2
    steps:
      - run: sleep 15s
