name: Contexts-vs-default-variables
on: push
jobs:
  prod-check:
    # this would be invalid: $GITHUB_REF == 'refs/heads/main'
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "ref is 1 $GITHUB_REF"
          echo "ref is 2 ${{ github.ref }}"

          