name: Defaults-Job-Level
on: push
jobs:
  job1:
    defaults:
      run:
        working-directory: .github
        shell: bash
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo $PWD