name: Defaults-Job-Level
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo $PWD
  job2:
    defaults:
      run:
        working-directory: .github
        shell: bash
    runs-on: ubuntu-latest
    steps:
      - run: echo $PWD