name: On-Workflow-Run
on:
  workflow_run:
    workflows: ["GitHub Actions Demo"]
    types: [completed]
  workflow_dispatch:
    inputs:
      input1:
        description: "input1 desc"
        required: true
        type: string
jobs:
  Triggered-Job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "github.event_name is ${{ github.event_name }}"
      - run: echo "inputs is ${{ toJSON(inputs) }}"
          