name: Printing-Contexts
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04]
    env:
      STRATEGY_CONTEXT: ${{ toJson(strategy) }}
      MATRIX_CONTEXT: ${{ toJson(matrix) }}
    steps:
      - name: Dump runner context
        id: step1
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        id: step2
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        id: step3
        run: echo "$MATRIX_CONTEXT"
      - name: Dump job context
        id: step4
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context 1
        id: step5
        run: echo "${{ toJson(steps) }}"
      - name: Dump steps context 2
        id: step6
        run: echo "${{ toJson(steps) }}"
