name: Repository-Dispatch-Called
on:
  repository_dispatch:
    types:
      - event1
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Printing client payload
        run: |
          echo "${{ toJson(github.event.client_payload) }}"
