name: Repository-Dispatch-Caller
on: [push]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            await github.rest.repos.createDispatchEvent({
              owner: context.repo.owner,
              repo: context.repo.repo,
              event_type: "event2",
              client_payload: {
                foo: "foo2",
                bar: "bar2"
              }
            });
