name: Repository-Dispatch-Called
on:
  repository_dispatch:
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Print input values
        run: |
          echo "Name: ${{ toJson(github.event.client_payload) }}"
          