name: Setting-Defaults
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: ls -la
  job2:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .github
    steps:
      - uses: actions/checkout@v4
      - run: ls -la