name: Python CI with Artifact Upload

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Generate dummy artifacts
      run: |
        mkdir -p output
        echo "Hello from GitHub Actions!" > output/message.txt
        echo "Timestamp: $(date)" >> output/message.txt

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: my-artifact-${{matrix.os}}
        path: output/

