name: Workflow-Call-Caller-Local
on: [push]
jobs:
  job1:
    uses: ./.github/workflows/workflow-call-called.yml
    with:
      foo: foo1
    secrets:
      bar: bar1
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: |
          echo "Reusable workflow output is ${{ needs.job1.outputs.output1 }}"
          