name: Workflow-Dispatch
on:
  workflow_dispatch:
    inputs:
      input1:
        description: "input1 desc"
        required: true
        type: string
      input2:
        description: "input2 desc"
        required: true
        type: environment
jobs:
  Triggered-Job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "github.event_name is ${{ github.event_name }}"
      - run: echo "inputs is ${{ toJSON(inputs) }}"
          