name: Workflow-Call-Caller-Local
on: [push]
jobs:
  job1:
    uses: ./.github/workflows/workflow-call-called.yml
    with:
      foo: foo-value
    secrets:
      bar: var-value
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: |
          echo "Got output: ${{ needs.job1.outputs.output1 }}"
          