name: Workflow-Call-Caller-Repo
on: [push]
jobs:
  job1:
    uses: asadehmitaw/gh_actions-reusable-workflows/.github/workflows/on-workflow-call.yml@main
    with:
      foo: foo2
    secrets:
      bar: bar2
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: |
          echo "workflow output 2: ${{ needs.job1.outputs.output1 }}"
          